### ISSUE TITLE
Get Travis to pass again

### ISSUE THREAD

**Issue by asppsa** [minad/moneta#103]
Hey @minad, so before I go ahead and merge all my various PRs, I thought I'd check that you're ok with me making whatever changes I deem necessary?

As per the title of this issue, I'm basically trying to get travis to green-light.  As such, after these commits, I'm bsically planning more of the same. That is, 

- possible changes to travis.yml 
- gemfile changes
- where moneta is depending on old versions of gems (as was the case with mongo), 
changes to the codebase as well (like the bzip2 changes)

Once travis is all green, I guess the next thing to do would be to modernise the rspec tests ...

**Comment by minad** [comment]
Sounds good! I will take a look before wie release a new version. Note that most of the tests are generated

Am 19. Mai 2016 03:35:21 MESZ, schrieb Alastair Pharo <notifications@github.com>:

**Comment by asppsa** [comment]
Done!
