### ISSUE TITLE
Mongo store not handling custom Mongo::Client properly

### ISSUE THREAD

**Issue by furrz** [minad/moneta#106]
Hello! I am having an issue using Moneta combined with rack and the `mongo` gem.

Moneta doesn't seem to be capable of using a pre-existing `Mongo::Client` instance in a Mongo store. It is trying to call a `db` method that does not exist. I am running the following code:

```
client = Mongo::Client.new(uri)
use Rack::Session::Moneta, store: Moneta.new(:Mongo, backend: client)
```

And recieving the following error:

```
/var/lib/gems/1.9.1/gems/moneta-0.8.0/lib/moneta/adapters/mongo/official.rb:44:in `initialize': undefined method `db' for #<Mongo::Client:0x80901720 cluster=127.0.0.1:27017> (NoMethodError)
    from /var/lib/gems/1.9.1/gems/moneta-0.8.0/lib/moneta.rb:125:in `new'
    from /var/lib/gems/1.9.1/gems/moneta-0.8.0/lib/moneta.rb:125:in `new'
    from app.rb:12:in `<class:App>'
```

If I've simply done something wrong in my code, I apologize for the trouble.

**Comment by asppsa** [comment]
Hi there,

Thanks for the report.  Can you let me know what version of the mongo gem you are using? Also, have you tried using git master?  There are a bunch of mongo changes in git that haven't made it into a release yet.
