### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by asppsa** [minad/moneta#108]
As @dbackeus mentioned in #87, it may well be time for a 1.0 release of moneta!  Does anyone see any reason not to just do this?

**Comment by asppsa** [comment]
@minad, I am thinking it might be a good idea to do the 1.0 release now while things are fairly stable and all the tests are passing, before any "radical" changes are introduced (rewriting the specs, updating the ruby versions that are supported, etc.).  Do you have any objections to this course of action?

**Comment by minad** [comment]
yes do that! great work!

**Comment by asppsa** [comment]
done!
