### ISSUE TITLE
ActiveSupport::Cache::Store adapter

### ISSUE THREAD

**Issue by metaskills** [minad/moneta#110]
Has there been any work to make a simple backend that wraps Rails.cache? This way we can take advantage of all the things configured in that backend with someone delegation for load/store, etc?

**Comment by asppsa** [comment]
Hello,

The answer to this is an emphatic yes!  This is mentioned in the README (see: https://github.com/minad/moneta#cache-store), but it seems to be a bit wrong at the moment (missing `=` and brackets).  A correct example would be something like:

~~~ ruby
config.cache_store = :moneta_store, { :store => :Memory }
~~~

Once you have it setup correctly, `Rails.cache` should be an instance of `ActiveSupport::Cache::MonetaStore`.

Hope that helps!  I'll try to get the docs corrected ASAP.

**Comment by metaskills** [comment]
Sorry no, let me restate the question. We want to continue to use either ActiveSupport's `:memcached_store` or the Dalli clients `:dalli_store`. The reason being is that these two stores have excellent support for Rails interfaces like `read_multi` and/or their conformance to the `LocalCache` protocol. I now do see that `ActiveSupport::Cache::MonetaStore` does indeed have these. 

However, I felt it might be more pragmatic to have a thin Moneta backend wrapper for any AS cache store. The primary motivator for this is so I can leverage existing configuration of Rails.cache. I do realize that this inherently says I trust either Dalli or Rails-Core more to keep up with changes to their stores for Rails better. That said, maybe a backend that wraps any AS store is more pragmatic. Thoughts?

**Comment by asppsa** [comment]
Ah sorry, I misunderstood.  So we are talking about a moneta adapter for `ActiveSupport::Cache::Store` objects.  I'm not aware of any existing efforts to do this, but like you say it should be pretty easy to do.  If you want to have a go and submit a PR, it would be much appreciated!

**Comment by asppsa** [comment]
@metaskills, I've just updated master with a new adapter called `ActiveSupportCache` (thanks largely to @minad for this!) that will hopefully meet your requirements.  If you have a chance to check it out, please let me know what you think!  You can instantiate it like so:

~~~ ruby
store = Moneta::Adapters::ActiveSupportCache.new(backend: ActiveSupport::Cache::SomeStore.new)
# or:
store = Moneta.build do
  # other stuff here, perhaps
  adapter :ActiveSupportCache, backend: ActiveSupport::Cache::SomeStore.new
end
~~~

`:backend` is optional when running in a Rails environment (defaults to `Rails.cache`).
