### ISSUE TITLE
Providing a redis client instead of a url

### ISSUE THREAD

**Issue by guyisra** [minad/moneta#111]
Currently, the redis adapter should be given a url of redis or a backend 

I couldn't figure it out from the code - is it possible to supply a redis client to be used by moneta?
We currently have a redis setup which includes namespacing, sentinels, instrumentation, connection pools, etc and it would be nice to have moneta use that instead of a bare Redis.new client

Is that possible, to supply an object that would bahve as a redis client?

**Comment by asppsa** [comment]
Hi there, yes this is possible.  To do it, you use the `:backend` option.  For example:

~~~ ruby
my_store = Moneta.build do
  adapter :Redis, :backend => Redis.new
end
~~~

Does that answer this for you?

**Comment by asppsa** [comment]
.... or even just:

~~~ ruby
my_store = Moneta.new :Redis, :backend => Redis.new
~~~

**Comment by guyisra** [comment]
Thanks!
Will open a new issue if issues arise

**Comment by guyisra** [comment]
Am I using this correctly? 
Doing 

```
my_store = Moneta.new :Redis, :backend => Redis.new
my_store.get 'test'
```

gives me
```
NoMethodError: undefined method `get' for #<Moneta::Transformer::MarshalPrefixKeyMarshalValue:0x007ff7ce6d86c0>
```
