### ISSUE TITLE
NoMethodError: undefined method `bad_request?' for #<Rack::ShowExceptions:0x007f6b20237cc8>

### ISSUE THREAD

**Issue by mopperwhite** [minad/moneta#117]
I set up moneta in config.ru like this:

```ruby
require 'moneta'
require 'rack/session/moneta'
use Rack::Session::Moneta, store: Moneta.new(:DataMapper, setup: AppConfig['database']['url'])
run Rack::Cascade.new [API, Web]
```
in which, API and Web are defined as
```ruby
class Web < Sinatra::Base
end
```
and
```ruby
class API < Grape::API
end
```

then I got a 

> NoMethodError: undefined method `bad_request?' for #<Rack::ShowExceptions:0x007f5ff427b298>

By the way, I launched the rack instance by using 'shotgun config.ru -p 3001'.

**Comment by asppsa** [comment]
I'm trying to reproduce this, but haven't managed to so far.  Do you have a reason for thinking that it is moneta that is causing the issue?  If so, please try to reduce your example down as much as possible (e.g. is the Datamapper adapter necessary for the issue to appear?) 

My setup is as follows (using ruby 2.3.4).  The main difference from your example is that I didn't know what database you were using with DataMapper, so I've specified SQLite. 

## Gemfile

~~~ ruby
source 'https://rubygems.org'
gem 'sinatra'
gem 'rack'
gem 'grape'
gem 'moneta'
gem 'shotgun'
gem 'datamapper'
gem 'dm-sqlite-adapter'
~~~

## config.ru

~~~ ruby
require 'rubygems'
require 'bundler/setup'
require 'sinatra'
require 'grape'
require 'moneta'
require 'rack/session/moneta'

class Web < Sinatra::Base
end

class API < Grape::API
end

use Rack::Session::Moneta, store: Moneta.new(:DataMapper, :repository => :default, :setup => 'sqlite::memory:')
run Rack::Cascade.new [API, Web]
~~~

## shell

~~~
$ bundle install
$ bundle exec shotgun config.ru 
== Shotgun/WEBrick on http://127.0.0.1:9393/
[2017-07-12 15:38:51] INFO  WEBrick 1.3.1
[2017-07-12 15:38:51] INFO  ruby 2.3.4 (2017-03-30) [x86_64-linux]
[2017-07-12 15:38:51] INFO  WEBrick::HTTPServer#start: pid=14882 port=9393
~~~

## some other shell

~~~ bash
curl http://127.0.0.1:9393/
~~~

## output

~~~ html
<!DOCTYPE html>
<html>
<head>
  <style type="text/css">
  body { text-align:center;font-family:helvetica,arial;font-size:22px;
    color:#888;margin:20px}
  #c {margin:0 auto;width:500px;text-align:left}
  </style>
</head>
<body>
  <h2>Sinatra doesn’t know this ditty.</h2>
  <img src='http://127.0.0.1:9393/__sinatra__/404.png'>
  <div id="c">
    Try this:
    <pre># in config.ru
class Shotgun::Loader::Web
  get &#x27;&#x2F;&#x27; do
    &quot;Hello World&quot;
  end
end
</pre>
  </div>
</body>
</html>
~~~

**Comment by mopperwhite** [comment]
@asppsa Well...I created a minimized project to test it...

[https://gist.github.com/mopperwhite/9bdf6dafe60a5810d15271a764c55ef2](config.ru)

Everything works fine with Sinatra

> $ curl http://localhost:3000/

> 0

but when it comes to Grape...

> $ curl http://localhost:3000/api/test

> Puma caught this error: undefined method `bad_request?' for #<Rack::ShowExceptions:0x00000001b7e778> (NoMethodError)
> (erb):145:in `pretty'
> /usr/lib/ruby/2.3.0/erb.rb:864:in `eval'
> /usr/lib/ruby/2.3.0/erb.rb:864:in `result'
> /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/show_exceptions.rb:96:in `pretty'
> /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/show_exceptions.rb:32:in `rescue in call'
> /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
> /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
> /var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
> /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/chunked.rb:54:in `call'
> /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/content_length.rb:15:in `call'
> /var/lib/gems/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
> /var/lib/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
> /var/lib/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
> /var/lib/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
> /var/lib/gems/2.3.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by mopperwhite** [comment]
@asppsa I figured that out.

The method 'session' is not provided by grape, and it has to be defined at 'helpers' of a Grape class.

But it is still wired that an exception raised in my server is not directly displayed. Instead, it seems that there is something wrong happened when rack tries to display the error message.

**Comment by asppsa** [comment]
Ok, well that doesn't sound like a moneta bug at any rate.  You might be able to work out what gem is causing the trouble by going through the backtrace.
