### ISSUE TITLE
Support only maintained branches of MRI

### ISSUE THREAD

**Issue by asppsa** [minad/moneta#135]
At present we are testing the following versions through Travis:

- 2.1
- 2.0.0
- 1.9.3
- jruby-1.7
- rbx-2

JRuby and RBX are "allowed failures", so we can't really say that we support these at the moment.

As noted by @brutuscat in #134, all of these MRI versions are "end of life" and no longer supported.  The suggestion is that in going forward, we only support versions of Ruby that are being maintained.  Practically, this means updating the `.travis.yml` each time there is a new branch of MRI.   The list of supported branches is [here][1].

For JRuby, and RBX, we don't really support these at the moment anyway, but we should probably only bother to "allow failures" against the latest release.

The issue with dropping 1.9.3 support is that there are some adapters & transformers that at present only work on 1.9.3, so we will either need to find new gems for, or we will need to drop support for them ...

[1]: https://www.ruby-lang.org/en/downloads/branches/

**Comment by asppsa** [comment]
Actually, I just checked the adapters and it looks like there was only tokyocabinet that was working on 1.9.3 and nowhere else (others are failing on all versions).  This may be rectified by 1592ad37746758450c1b9de6ba37d45a76190313.

**Comment by asppsa** [comment]
An alternative rationale would be to target ruby versions supported by significant projects that Moneta is intended to work with.  The most obvious such project would be Rails.  v5 needs `>= 2.2.2`; v6 will require `> = 2.4.1`.

**Comment by asppsa** [comment]
- Sinatra requires `>= 2.2.0`
- Rack requires `>= 2.2.2`

**Comment by brutuscat** [comment]
@asppsa 2.2 will be EOL by the end of this month. So all these projects would probably deprecate it soon too.

**Comment by asppsa** [comment]
I'm sure you are right, but I'm wondering whether it makes sense for Moneta to be a first-mover.

**Comment by brutuscat** [comment]
@asppsa so what if we follow Rack with a 1 quarter of "lag"? Sinatra and Rails both depend on it, so it looks like the "building base block".

**Comment by asppsa** [comment]
... and Moneta can be used directly with Rack also, so that seems to fit well!

I will ask the Rack people when they plan to drop 2.2 support.  If they will do it at the end of the month, then we probably don't need to do anything

**Comment by asppsa** [comment]
I wrote to the rack people via their Google group, but have yet to receive a response.  In the meantime, I see that [Rails 5.2 RC2](https://rubygems.org/gems/rails/versions/5.2.0.rc2) will support 2.2.2+.  Based on this, I think we should follow suit.

**Comment by brutuscat** [comment]
@asppsa it stayed alive for while! https://github.com/rack/rack/commit/d81a5d3bdd20d80527164705b1fcfd0b7f4be6cd#diff-135f8e9ca96a33986047ac5b43819431
