### ISSUE TITLE
Getting and issue (Load Error) not sure

### ISSUE THREAD

**Issue by ScottR95** [minad/moneta#137]
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require': cannot load such file -- moneta/memory (LoadError)

from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernal_require.rb:133:in 'rescue in require
from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernal_require.rb:39:in 'require'

**Comment by asppsa** [comment]
Hi,

Could you please let us know the following:

* Moneta version you are using; and
* A small snippet of Ruby code that we can use to generate the problem.

Thanks.
