### ISSUE TITLE
ActiveRecord adapter does not work with forking web servers (e.g. Puma)

### ISSUE THREAD

**Issue by bjeanes** [minad/moneta#159]
Using the ActiveRecord adapter in a forking web server will cause interactions with the Moneta store to fail with a `NoMethodError` (ActiveRecord 5, at least).

The problem is that the adapter stores the connection pool in the initializer but after a server forks, the connection pool has to be discarded and re-created in each process. [The behaviour of a discarded connection pool is undefined](https://github.com/rails/rails/blob/e7717ec7a09ca83f92a9819303f7a93e038a2679/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L458-L460) but for sure calling `with_connection` results in accessing a nil instance variable [on this line within AR's connection pool](https://github.com/rails/rails/blob/e7717ec7a09ca83f92a9819303f7a93e038a2679/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L412).

Here's an example exception with stacktrace: https://sentry.io/share/issue/51fc2ab0456447a19f59018db1a1c971/ (URL will probably only work for ~30 days, though). You have to expand stack trace to "full" to see the origin of the exception.

This can be worked around by doing something like the following after forking:

``` ruby
adapter.instance_variable_set(
  :@connection_pool,
  ActiveRecord::Base.connection_pool,
)
```

**Comment by bjeanes** [comment]
This is particularly important since the feature matrix lists this as "multiprocess" compatible. It is, but only if you create the instance after forking or mess with private internals.

**Comment by asppsa** [comment]
Ok, looks like the way to fix this will be to replace that `@connection_pool` variable with a function. This also raises that we should probably have a test that involves a call to `fork`.  Thanks for the report!

**Comment by bjeanes** [comment]
Alternatively/additionally, factor out the setting of `@connection_pool` from initializer and into a separate method which can be called at anytime to reconnect.

**Comment by asppsa** [comment]
Yes, s/function/method/
