### ISSUE TITLE
Key/value iterator (#each, #keys)

### ISSUE THREAD

**Issue by dariocravero** [minad/moneta#61]
Hi,

I'm currently using Moneta as a backend for I18n and it's missing a `keys` method interface [needed](https://github.com/svenfuchs/i18n/blob/master/lib/i18n/backend/key_value.rb#L12) by that gem as to what's the minimum a backend should support to comply.

I reckon it might be of good use on other scenarios anyway, however, is there any reason why it isn't available already?

I'll be happy to work on a patch if this makes sense.

Thanks,
Darío

PS: I'm patching it right now for the `Memory` adapter as follows:

```
module Moneta
  class Proxy
    def keys
      adapter.keys
    end
  end

  module HashAdapter
    # Expand on https://github.com/minad/moneta/blob/master/lib/moneta/mixins.rb
    def keys
      @backend.keys
    end
  end
end
```

**Comment by brutuscat** [comment]
@dariocravero I'm also interested in this and I would like to help.

@minad could you elaborate a bit more about:
> However you could add it as an additional operation

**Comment by brutuscat** [comment]
@minad would make sense to have to add support for like using the same approach as `weakIncrement`? Also it should always return a lazy enumerator?

**Comment by dariocravero** [comment]
Thanks @brutuscat, I had completely forgotten about this... :/ It would be good to see it in ;)

**Comment by minad** [comment]
@dariocravero @brutuscat Yes, atomic increment is an optional method for example. Iterators could be implemented in the same way.

**Comment by irregulator** [comment]
Hi, that would be a very useful feature indeed. Are there still plans of implementing it? Any caveat pushing back the implementation? Thanks.

**Comment by brutuscat** [comment]
@irregulator in my case I never found time to push this forward and since the other project that needs it never managed to attract enough interest, well it is here in my todo list...

**Comment by brutuscat** [comment]
I will be using this issue to layout my notes for this:

- it will implement the `each` method [using enumerator](https://blog.arkency.com/2014/01/ruby-to-enum-for-enumerator/)
- change master/lib/moneta/weak.rb and add a WeakEnumerator class
 - hook into the base proxy so to log "stored keys" - "deleted keys". This will be the weak implementation.
- it will "delegate" to @backend.keys if the backend quacks like a hash
- it will implement batch loading in backends such as AR, probably using lazy enums in batches
- it can be slow or blocking in some backends (?)
