### ISSUE TITLE
TokyoTyrant + KyotoTycoon append method missing.

### ISSUE THREAD

**Issue by elico** [minad/moneta#73]
TokyoTyrant + KyotoTycoon have the same interface with maybe minor changes if there are.
I am working on something and found out that the KyotoTycoon gem contains the "append" method for a key which allows more flexibility in couple matters.

It would help me a lot if you could add it into the TokyoTyrant module or to a different module such as KyotoTycoon.

Thanks,
Eliezer

**Comment by minad** [comment]
I don't think we should add that since we only implement methods that most of the dbs support.

**Comment by elico** [comment]
Well it's your design and software. and In any case thanks for the time spent on thinking.
