### ISSUE TITLE
Adding column to backend feature matrix indicating if option requires external software 

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [minad/moneta#78]
Would it be possible to add another column to the backend feature matrix which tells us if the option requires external software to be installed or not? Possibly also a link to website or install instructions for that backend.

Example:
`PStore: -`
`Cassandra: [Download instructions](http://cassandra.apache.org/)`

It would be of great help if you are, like me, developing an app which can't depend on externally installed software.

**Comment by minad** [comment]
yes please do. external software == server software && external software != separate gem? Also what about native code? Maybe we should add the external software column and add a remark to the gem column if it contains native code.

It would be great if you could add it.

**Comment by stephan-nordnes-eriksen** [comment]
I can contribute, but I do not know enough about all of these to provide a complete list.

**Comment by minad** [comment]
Well for this you have the internet :) I have no time to do that for you. Please reopen if you have a pull request.
