### ISSUE TITLE
Adapter: sequel with psql

### ISSUE THREAD

**Issue by hggh** [minad/moneta#80]
I was trying to use trocla with Sequal backend. (tracla uses moneta) with Postgres I got the following error:

Action failed with the following message: PG::UndefinedObject: ERROR:  type "blob" does not exist
LINE 1: ...OT EXISTS "trocla" ("k" text NOT NULL PRIMARY KEY, "v" Blob)

With MySQL there was no error. I applied the following patch:

```
diff --git a/lib/moneta/adapters/sequel.rb b/lib/moneta/adapters/sequel.rb
index d61898d..f47b1cc 100644
--- a/lib/moneta/adapters/sequel.rb
+++ b/lib/moneta/adapters/sequel.rb
@@ -28,7 +28,7 @@ module Moneta
           end
         @backend.create_table?(table) do
           String :k, null: false, primary_key: true
-          Blob :v
+          File :v
         end
         @table = @backend[table]
       end
```

After using that code the postgres backend started to work. I have also tested mysql and it's working.

**Comment by minad** [comment]
What is the difference between file and blob in mysql?

**Comment by hggh** [comment]
there is no difference. file is mapped into blob

**Comment by dje4om** [comment]
Hi,
just had the same issue with trocla and this fix works, i tested it with postgresql backend and mysql backend, the column still in blob type, it seems to be describe here : 
http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html
