### ISSUE TITLE
Cannot use moneta as Rails Session Store

### ISSUE THREAD

**Issue by InHiding** [minad/moneta#84]
Hi,

I've tried to configure moneta as session store for my rails application.

First I used the (3)way the documentation suggests:

```
# Only by adapter name
config.cache_store :moneta_store, store: :Memory

# Use Moneta.new
config.cache_store :moneta_store, store: Moneta.new(:Memory)

# Use the Moneta builder
config.cache_store :moneta_store, store: Moneta.build do
  use :Expires
  adapter :Memory
end
```

None of it worked and failed with this error: 
gems/moneta-0.8.0/lib/moneta/builder.rb:7:in `initialize': No block given (ArgumentError)

Then I tried:
```
config.session_store :moneta_store, store: :MongoOfficial
```

This time it failed with:
ruby-2.2.2/gems/railties-4.2.2/lib/rails/application/configuration.rb:176:in `const_get': uninitialized constant ActionDispatch::Session::MonetaStore (NameError)

I made anything wrong?

My system:
Ruby 2.2.2
Rails 4.2.2
Mongo 1.12.3

regards,
Giuliano

**Comment by wamaral** [comment]
Yeah, I could reproduce this issue, with this exact configuration.

**Comment by romeuhcf** [comment]
Same here!

**Comment by minad** [comment]
I think you have to use

~~~
require 'action_dispatch/middleware/session/moneta_store'
~~~
