### ISSUE TITLE
Moneta with sequel adapter connection pooling

### ISSUE THREAD

**Issue by irregulator** [minad/moneta#85]
Hello,

We've been trying to use moneta (as used by trocla) with 'Sequel' adapter as part of our puppet configuration management. Within a puppet manifest we call trocla to land passphrases to our machines. During puppet catalog compilation the puppet master makes sql queries to the sql backend in order to fetch the passphrases.

According to http://sequel.jeremyevans.net/ sequel adapter provides connection pooling. Thus we would expect moneta and sequel to reuse existing open connections to sql.

Instead, during puppet run we observe that puppet master opens as many connections as the number of sql SELECT that correspond to passphrases' fetch.

This poses a problem in terms of scaling. Because puppet master needs to open NxM connections, where N is the number of trocla secrets within a puppet manifest and M is the number of machines this manifest is applied to.

We have already hit our number of max_connections configured in our database server and before just augmenting that parameter we would like to understand how moneta and sequel actually handle the connections.

We also tried to set ":max_connections: X" as pointed out in http://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html so as the connection pool in each puppet master uses up to X connections but it seems this option is not honoured. In each puppet run puppet master will open sql connections equal to the number of sql values that need to be fetched. Does this means that for every query to the sql backend moneta creates a new connection pool?

Thanks

**Comment by asppsa** [comment]
Closing this as I am guessing this is no longer an issue.  Feel free to reopen
