### ISSUE TITLE
Expire will be reset when fetching cache with expires_in

### ISSUE THREAD

**Issue by tony612** [minad/moneta#89]
I use moneta with redis, and use it as cache store of rails.

When I use `Rails.cache.fetch("key", expires_in: 1.hour) { ... }` , I found expires of cache will be reset each time the code is run, which is not what I expect.

Then I found moneta will call `load` and `load` will reset the expires as https://github.com/minad/moneta/blob/master/lib/moneta/adapters/redis.rb#L39

Maybe we should just delete `expires_in` param in `active_support/cache/moneta_store.rb`? For example, in this method https://github.com/minad/moneta/blob/master/lib/active_support/cache/moneta_store.rb#L35

**Comment by minad** [comment]
I think it is correct that fetch changes the expires value. Please check the rails documentation.

**Comment by tony612** [comment]
@minad Sorry, I didn't find where the documentation says something like "fetch changes the expires value"
