### ISSUE TITLE
multi process access for :memory backend

### ISSUE THREAD

**Issue by rrphotosoft** [minad/moneta#93]
Hi,
I've reached Moneta, because I need to store some data on startup in my Rails application, that will be accessed during certain requests. Speed is the only requirement. Initially I thought of just using a simple initializer and storing the data there, but I found several discussions on stackoverflow indicating that a production environment has MULTIPLE RAILS PROCESSES, and so each process would recieve its own copy of the initializer variable.(I can't have that.)
I'm interested in the pure :memory backend offered with Moneta, but need to know whether a key is in anyway tied to the process/thread that writes the key or whether it can be safely accessed across multiple processes.
Thanks,
RRphotosoft

**Comment by minad** [comment]
please take a look at https://github.com/minad/moneta#backend-feature-matrix

this should answer your question
