### ISSUE TITLE
expires_in usage for in Memory or LRUHash store

### ISSUE THREAD

**Issue by rajatjindal** [minad/moneta#96]
Its more of a question then a issue, do we support expires_in for in memory or LRUHash stores?

I see in table below you mentioned, native expire not supported, but is there any way to set expiration?

**Comment by abargnesi** [comment]
I did not find any mention of `expires_in` except for in [lib/active_support/cache/moneta_store.rb](https://github.com/minad/moneta/blob/master/lib/active_support/cache/moneta_store.rb#L54).

To establish an expiring Memory or LRUHash store you can pass the `expires` option to `Moneta.new`. The option value should be the `Integer` number of seconds until an object is expired from the store.

```ruby
require 'moneta'

# Create a LRUHash where items expire if older than 30 seconds.
hash = Moneta.new(:LRUHash, expires: 30)
hash[:foo] = :bar
hash[:foo] # => :bar
# Wait 30 seconds...
hash[:foo] # => nil
```

[example terminal screencast](https://asciinema.org/a/44585)

**Comment by asppsa** [comment]
Hi,

Sorry for the extremely long silence on this!  It is possible to add expiry to an adapter that doesn't support it natively.  This is accomplished by using [the `Expires` proxy](http://www.rubydoc.info/github/minad/moneta/master/Moneta/Expires) like so:

~~~ ruby
store = Moneta.build do
  use :Expires
  adapter :Memory # or whatever
end
~~~

You can also use `expires: true` with the `Moneta.new` shorthand:

~~~ ruby
store = Moneta.new(:Memory, expires: true)
~~~

Both methods will create stores that don't expire keys by default, but which do accept an `expires` (not `expires_in`) option for various actions (`store`, `load`, 'fetch', `key?`).  E.g.,

~~~ ruby
store.store('x', 1, expires: 1) # expires value is a numeric value in seconds
# 1 second later
store.load('x') # => nil
~~~

You can also specify a default expiry value as @abargnesi says.  In this case, you can still specify an expiry value on `store`, etc., in which case the sepcified expiry will override the default.
